modLoader="javafml"
loaderVersion="[43,)"
license="GPLv3"

[[mods]]
modId="incineratorstryhard"
version="1.19.2-1.0.1"
displayName="Cataclysm: Incinerator's Try Hard"
authors="Rinko1231"
description='''
Custom the damage and charging time of the Incinerator!
'''